const data = [
  {
    name: "Game of Thrones",
    img: "https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg",
    pub: "2011-2019",
    stars: "9.2",
    rates: "2.2M",
    episodes: "73 eps",
  },
  {
    name: "Breaking Bad",
    img: "https://m.media-amazon.com/images/M/MV5BYmQ4YWMxYjUtNjZmYi00MDQ1LWFjMjMtNjA5ZDdiYjdiODU5XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg",
    pub: "2008-2013",
    stars: "9.5",
    rates: "2.1M",
    episodes: "62 eps",
  },
  {
    name: "Stranger Things",
    img: "https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
    pub: "2016-2025",
    stars: "8.7",
    rates: "1.3M",
    episodes: "42 eps",
  },
  {
    name: "Friends",
    img: "https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
    pub: "1994-2004",
    stars: "8.9",
    rates: "1.1M",
    episodes: "234 eps",
  },
  {
    name: "Sherlock",
    img: "https://m.media-amazon.com/images/M/MV5BMWEzNTFlMTQtMzhjOS00MzQ1LWJjNjgtY2RhMjFhYjQwYjIzXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_FMjpg_UX1000_.jpg",
    pub: "2010-2017",
    stars: "9.1",
    rates: "978K",
    episodes: "15 eps",
  },
  {
    name: "Chernobyl",
    img: "https://m.media-amazon.com/images/M/MV5BNTdkN2QwMDItMDVhNS00ZjFiLWEzNTctMzY5ODQzYWNkMDllXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg",
    pub: "2019",
    stars: "9.3",
    rates: "836K",
    episodes: "5 eps",
  },
  {
    name: "Dexter",
    img: "https://m.media-amazon.com/images/M/MV5BZjkzMmU5MjMtODllZS00OTA5LTk2ZTEtNjdhYjZhMDA5ZTRhXkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_.jpg",
    pub: "2006-2013",
    stars: "8.7",
    rates: "753K",
    episodes: "96 eps",
  },
  {
    name: "The Office",
    img: "https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg",
    pub: "2005-2013",
    stars: "9.0",
    rates: "683K",
    episodes: "188 eps",
  },
  {
    name: "Black Mirror",
    img: "https://m.media-amazon.com/images/M/MV5BZTgyNTBkNzctN2I3NC00NTA1LWJiMDMtYzA2MmYyZjc1NWQzXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_FMjpg_UX1000_.jpg",
    pub: "2011 - ",
    stars: "8.7",
    rates: "622K",
    episodes: "28 eps",
  },
  {
    name: "Peaky Blinders",
    img: "https://m.media-amazon.com/images/M/MV5BZjYzZDgzMmYtYjY5Zi00YTk1LThhMDYtNjFlNzM4MTZhYzgyXkEyXkFqcGdeQXVyMTE5NDQ1MzQ3._V1_FMjpg_UX1000_.jpg",
    pub: "2013-2022",
    stars: "8.8",
    rates: "622K",
    episodes: "36 eps",
  },
  {
    name: "Better Call Saul",
    img: "https://m.media-amazon.com/images/M/MV5BZDA4YmE0OTYtMmRmNS00Mzk2LTlhM2MtNjk4NzBjZGE1MmIyXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg",
    pub: "2015-2022",
    stars: "9.0",
    rates: "621K",
    episodes: "63 eps",
  },
  {
    name: "True Detective",
    img: "https://m.media-amazon.com/images/M/MV5BNWIxMjA0ZWUtMDY1MS00NzFkLTkxOTQtYWE2YjFmZjE4NDJjXkEyXkFqcGdeQXVyMTA3MzQ4MTc0._V1_.jpg",
    pub: "2014 - ",
    stars: "8.9",
    rates: "618K",
    episodes: "30 eps",
  },
  {
    name: "The Boys",
    img: "https://m.media-amazon.com/images/M/MV5BZGUyNzM0M2EtMjA1Zi00MWJhLWI2ZWEtNzE3OTgyMTBkN2IzXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_QL75_UY281_CR18,0,190,281_.jpg",
    pub: "2019 - ",
    stars: "8.7",
    rates: "613K",
    episodes: "32 eps",
  },
  {
    name: "The Queen's Gambit",
    img: "https://m.media-amazon.com/images/M/MV5BYTFmN2E3YjYtZWMxMS00ZjFiLWI2NjUtNWQwNDhhNDA2MTUyXkEyXkFqcGdeQXVyMTM0NTc2NDgw._V1_.jpg",
    pub: "2020",
    stars: "8.5",
    rates: "526K",
    episodes: "7 eps",
  },
  {
    name: "House of Cards",
    img: "https://m.media-amazon.com/images/M/MV5BNmM4ODU1MzItODYyYi00Y2U0LWFjZjItYTRhZWIwOGMyZTRhXkEyXkFqcGdeQXVyNjc2NTQ4Nzk@._V1_FMjpg_UX1000_.jpg",
    pub: "2013 - 2018",
    stars: "8.6",
    rates: "525K",
    episodes: "73 eps",
  },
];
export default data;
